# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0002_auto_20160908_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibonacci',
            name='id',
        ),
        migrations.AlterField(
            model_name='fibonacci',
            name='parameter',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
